### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by xjqxziii** [ImDarkTom/ComfyUIMini#13]
[07:01:22] [INFO] Found 1 valid workflows in the workflow folder.
[07:01:22] [SUCCESS] Running on http://*...
/.../ComfyUIMini-main/src/utils/objectInfoUtils.js:9
        for (const [inputName, inputInfo] of Object.entries(nodeInfo.input.required)) {
                                                    ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at loadObjectInfoMap (/.../ComfyUIMini-main/src/utils/objectInfoUtils.js:9:53

**Comment by ImDarkTom** [comment]
What ComfyUI version are you running? You can check at `http://(comfyui url)/system_stats`.

**Comment by Lumoria** [comment]
i get the same error. Running: [ComfyUI v0.2.4-11-g9ee0a65]  python=3.11.9, pytorch=2.4.1+cu124

**Comment by ImDarkTom** [comment]
Is there any console output in the latest version?

**Comment by saxesn** [comment]
[11:03:19] [INFO] Found 1 valid workflows in the workflow folder.
[11:03:19] [SUCCESS] Running on http://127.0.0.1:3000
[11:03:19] [SUCCESS] ComfyUI is running.
[11:03:19] [SUCCESS] ComfyUI version: v0.2.5-2-g770ab20
d:\ComfyUIMini\src\utils\objectInfoUtils.ts:14
        for (const [inputName, inputInfo] of Object.entries(nodeInfo.input.required)) {
                                                    ^
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at getProcessedObjectInfo (d:\ComfyUIMini\src\utils\objectInfoUtils.ts:14:53)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async d:\ComfyUIMini\src\routes\comfyUIRouter.ts:68:33

**Comment by Hujikuio** [comment]
> [11:03:19] [INFO] Found 1 valid workflows in the workflow folder. [11:03:19] [SUCCESS] Running on http://127.0.0.1:3000 [11:03:19] [SUCCESS] ComfyUI is running. [11:03:19] [SUCCESS] ComfyUI version: v0.2.5-2-g770ab20 d:\ComfyUIMini\src\utils\objectInfoUtils.ts:14 for (const [inputName, inputInfo] of Object.entries(nodeInfo.input.required)) { ^ TypeError: Cannot convert undefined or null to object at Function.entries () at getProcessedObjectInfo (d:\ComfyUIMini\src\utils\objectInfoUtils.ts:14:53) at processTicksAndRejections (node:internal/process/task_queues:105:5) at async d:\ComfyUIMini\src\routes\comfyUIRouter.ts:68:33

exact same output for me as well

**Comment by dpm316** [comment]
I'm getting the same error with the latest ComfyUI and latest ComfyUIMini immediately after install with the built-in workflow that comes with this app.

steps to repro:
start ComfyUI
start ComfyUIMini
navigate to http://localhost:3000
select ComfyUI Default Workflow

console output:
C:\Users\dpm316\github\ComfyUIMini>npm start

> comfyuimini@1.4.0 start
> ts-node src/index.ts

[13:57:38] [INFO] Found 1 valid workflows in the workflow folder.
[13:57:38] [SUCCESS] Running on http://192.168.50.166:3000/
[13:57:38] [SUCCESS] ComfyUI is running.
[13:57:38] [SUCCESS] ComfyUI version: v0.2.4-12-g669d9e4
C:\Users\dpm316\github\ComfyUIMini\src\utils\objectInfoUtils.ts:14
        for (const [inputName, inputInfo] of Object.entries(nodeInfo.input.required)) {
                                                    ^
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at getProcessedObjectInfo (C:\Users\dpm316\github\ComfyUIMini\src\utils\objectInfoUtils.ts:14:53)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\dpm316\github\ComfyUIMini\src\routes\comfyUIRouter.ts:68:33

**Comment by ImDarkTom** [comment]
What comes up when you go to `<comfyui url>/api/object_info`?

**Comment by saxesn** [comment]
When calling the URL, a JSON with all nodes is output. Here’s a shortened part of it:

```
{
    "KSampler": {
        "input": {
            "required": {
                "model": [
                    "MODEL",
                    {
                        "tooltip": "The model used for denoising the input latent."
                    }
                ],
                "seed": [
                    "INT",
                    {
                        "default": 0,
                        "min": 0,
                        "max": 18446744073709551615,
                        "tooltip": "The random seed used for creating the noise."
                    }
                ],
                "steps": [
                    "INT",
                    {
                        "default": 20,
                        "min": 1,
                        "max": 10000,
                        "tooltip": "The number of steps used in the denoising process."
                    }
                ],
                "cfg": [
                    "FLOAT",
                    {
                        "default": 8.0,
                        "min": 0.0,
                        "max": 100.0,
                        "step": 0.1,
                        "round": 0.01,
                        "tooltip": "The Classifier-Free Guidance scale balances creativity and adherence to the prompt. Higher values result in images more closely matching the prompt however too high values will negatively impact quality."
                    }
                ],
                "sampler_name": [
                    [
                        "euler",
                        "euler_cfg_pp",
                        "euler_ancestral",
                        "euler_ancestral_cfg_pp",
                        "heun",
                        "heunpp2",
                        "dpm_2",
                        "dpm_2_ancestral",
                        "lms",
                        "dpm_fast",
                        "dpm_adaptive",
                        "dpmpp_2s_ancestral",
                        "dpmpp_2s_ancestral_cfg_pp",
                        "dpmpp_sde",
                        "dpmpp_sde_gpu",
                        "dpmpp_2m",
                        "dpmpp_2m_cfg_pp",
                        "dpmpp_2m_sde",
                        "dpmpp_2m_sde_gpu",
                        "dpmpp_3m_sde",
                        "dpmpp_3m_sde_gpu",
                        "ddpm",
                        "lcm",
                        "ipndm",
                        "ipndm_v",
                        "deis",
                        "ddim",
                        "uni_pc",
                        "uni_pc_bh2"
                    ],
                    {
                        "tooltip": "The algorithm used when sampling, this can affect the quality, speed, and style of the generated output."
                    }
                ],
                "scheduler": [
                    [
                        "normal",
                        "karras",
                        "exponential",
                        "sgm_uniform",
                        "simple",
                        "ddim_uniform",
                        "beta",
                        "linear_quadratic"
                    ],
                    {
                        "tooltip": "The scheduler controls how noise is gradually removed to form the image."
                    }
                ],
                "positive": [
                    "CONDITIONING",
                    {
                        "tooltip": "The conditioning describing the attributes you want to include in the image."
                    }
                ],
                "negative": [
                    "CONDITIONING",
                    {
                        "tooltip": "The conditioning describing the attributes you want to exclude from the image."
                    }
                ],
                "latent_image": [
                    "LATENT",
                    {
                        "tooltip": "The latent image to denoise."
                    }
                ],
                "denoise": [
                    "FLOAT",
                    {
                        "default": 1.0,
                        "min": 0.0,
                        "max": 1.0,
                        "step": 0.01,
                        "tooltip": "The amount of denoising applied, lower values will maintain the structure of the initial image allowing for image to image sampling."
                    }
                ]
            }
        },
        "input_order": {
            "required": [
                "model",
                "seed",
                "steps",
                "cfg",
                "sampler_name",
                "scheduler",
                "positive",
                "negative",
                "latent_image",
                "denoise"
            ]
        },
        "output": [
            "LATENT"
        ],
        "output_is_list": [
            false
        ],
        "output_name": [
            "LATENT"
        ],
        "name": "KSampler",
        "display_name": "KSampler",
        "description": "Uses the provided model, positive and negative conditioning to denoise the latent image.",
        "python_module": "nodes",
        "category": "sampling",
        "output_node": false,
        "output_tooltips": [
            "The denoised latent."
        ]
    },
    "CLIPTextEncode": {
        "input": {
            "required": {
                "text": [
                    "STRING",
                    {
                        "multiline": true,
                        "dynamicPrompts": true,
                        "tooltip": "The text to be encoded."
                    }
                ],
                "clip": [
                    "CLIP",
                    {
                        "tooltip": "The CLIP model used for encoding the text."
                    }
                ]
            }
        },
        "input_order": {
            "required": [
                "text",
                "clip"
            ]
        },
        "output": [
            "CONDITIONING"
        ],
        "output_is_list": [
            false
        ],
        "output_name": [
            "CONDITIONING"
        ],
        "name": "CLIPTextEncode",
        "display_name": "CLIP Text Encode (Prompt)",
        "description": "Encodes a text prompt using a CLIP model into an embedding that can be used to guide the diffusion model towards generating specific images.",
        "python_module": "nodes",
        "category": "conditioning",
        "output_node": false,
        "output_tooltips": [
            "A conditioning containing the embedded text used to guide the diffusion model."
        ]
    },
    "easy XYInputs: NegativeCond": {
        "input": {
            "optional": {
                "negative_1": [
                    "CONDITIONING"
                ],
                "negative_2": [
                    "CONDITIONING"
                ],
                "negative_3": [
                    "CONDITIONING"
                ],
                "negative_4": [
                    "CONDITIONING"
                ]
            }
        },
        "input_order": {
            "optional": [
                "negative_1",
                "negative_2",
                "negative_3",
                "negative_4"
            ]
        },
        "output": [
            "X_Y"
        ],
        "output_is_list": [
            false
        ],
        "output_name": [
            "X or Y"
        ],
        "name": "easy XYInputs: NegativeCond",
        "display_name": "XY Inputs: NegCond //EasyUse",
        "description": "",
        "python_module": "custom_nodes.ComfyUI-Easy-Use",
        "category": "EasyUse/XY Inputs",
        "output_node": false
    }
}
```
The problem seems to come from nodes that only have optional inputs but no required ones. For example, the node "easy XYInputs: NegativeCond" is missing a required object under input, which can cause processing issues.

**Comment by ImDarkTom** [comment]
Thank you, I haven't tried using custom nodes before so I wasn't aware that a node could come without any required inputs.

**Comment by dpm316** [comment]
@ImDarkTom Thanks for the quick fix! Works great now! Fantastic app!

**Comment by ImDarkTom** [comment]
Fix is now included in the latest release.
