### ISSUE TITLE
Support for ComfyUI's built in https option, web socket error and crash

### ISSUE THREAD

**Issue by DrMechanica** [ImDarkTom/ComfyUIMini#16]
This is a very nifty thing you've built and I'm excited to use it, but currently I'm having trouble making it work due (I believe) to TLS issues. I'm having a similar issue to #14 , although I'm not using nginx to forward https to http, but instead using ComfyUI's built in https option. From what I can tell, because the certificate is self-signed ComfyUIMini doesn't trust it, can't generate, and then appears to crash. 

Steps to reproduce:
1. Changed comfyui_url in config json to "https://127.0.0.1:8188" (turns out this step doesn't matter. Same crash with 'http://...').
2. npm start, access from mobile device
3. run workflow, receive websocket error
    Output:
```
WebSocket error when generating image: Error: socket hang up
    at Socket.socketOnEnd (node:_http_client:530:25)
    at Socket.emit (node:events:519:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'ECONNRESET'
}
```
4. Tap 'cancel' on mobile device, crash
    Output:
```
C:\Users\DocM\Documents\ML_AI\ComfyUIMini\node_modules\axios\lib\core\AxiosError.js:92
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
AxiosError: unable to verify the first certificate
    at Function.AxiosError.from (C:\Users\DocM\Documents\ML_AI\ComfyUIMini\node_modules\axios\lib\core\AxiosError.js:92:14)
    at RedirectableRequest.handleRequestError (C:\Users\DocM\Documents\ML_AI\ComfyUIMini\node_modules\axios\lib\adapters\http.js:620:25)
    at RedirectableRequest.emit (node:events:519:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (C:\Users\DocM\Documents\ML_AI\ComfyUIMini\node_modules\follow-redirects\index.js:49:24)
    at ClientRequest.emit (node:events:507:28)
    at ClientRequest.emit (node:domain:489:12)
    at emitErrorEvent (node:_http_client:103:11)
    at TLSSocket.socketErrorListener (node:_http_client:506:5)
    at TLSSocket.emit (node:events:507:28)
    at Axios.request (C:\Users\DocM\Documents\ML_AI\ComfyUIMini\node_modules\axios\lib\core\Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async interruptGeneration (C:\Users\DocM\Documents\ML_AI\ComfyUIMini\src\utils\comfyAPIUtils.ts:362:22)
    at async C:\Users\DocM\Documents\ML_AI\ComfyUIMini\src\routes\comfyUIRouter.ts:61:34 {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 10000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'ComfyUIMini/1.4.0',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'https://127.0.0.1:8188',
    method: 'post',
    url: '/interrupt',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Array],
      timeout: undefined,
      abort: undefined
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/interrupt',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '127.0.0.1',
      port: '8188',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/interrupt'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      _header: 'POST /interrupt HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: ComfyUIMini/1.4.0\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 127.0.0.1:8188\r\n' +
        'Connection: keep-alive\r\n' +
        'Content-Length: 0\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/interrupt',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [TLSSocket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://127.0.0.1:8188/interrupt',
    _timeout: null,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
      at TLSSocket.emit (node:events:507:28)
      at TLSSocket.emit (node:domain:489:12)
      at TLSSocket._finishInit (node:_tls_wrap:1078:8)
      at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:864:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
  }
}
```

Thanks for your help.

**Comment by ImDarkTom** [comment]
The latest release should fix this, just set `reject_unauthorised_cert` to false and you should be able to use a https:// ComfyUI url.

**Comment by axiopaladin** [comment]
I can confirm that I can connect to a ComfyUI server over HTTPS, with the self-signed certificate that [ComfyUI recommends for private use](https://github.com/comfyanonymous/ComfyUI#how-to-use-tlsssl), so I think this issue can be closed now?

On a related tangent, I'd love to see a similarly simple option for hosting ComfyUIMini with HTTPS (probably using a similar cert), as Android Firefox blocks image downloads from HTTP sites if you don't disable HTTPS-Only mode for all tabs. (And let me tell you, it took me a hot minute to track down the origin of that problem; it never threw any visible messages about *why* downloads would always instantly fail.)

**Comment by ImDarkTom** [comment]
This is now implemented in the latest release.
