### ISSUE TITLE
Error: Cannot find module 'node:crypto'

### ISSUE THREAD

**Issue by nitrousoxXxide** [ImDarkTom/ComfyUIMini#2]
`xxx@xxx:~/StableDiffusion/ComfyUIMini$ node .
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:crypto'
Require stack:
- /home/xxx/StableDiffusion/ComfyUIMini/node_modules/uuid/dist/rng.js
- /home/xxx/StableDiffusion/ComfyUIMini/node_modules/uuid/dist/v1.js
- /home/xxx/StableDiffusion/ComfyUIMini/node_modules/uuid/dist/index.js
- /home/xxx/StableDiffusion/ComfyUIMini/src/utils/generation.js
- /home/xxx/StableDiffusion/ComfyUIMini/src/routes/wsRouter.js
- /home/xxx/StableDiffusion/ComfyUIMini/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/xxx/StableDiffusion/ComfyUIMini/node_modules/uuid/dist/rng.js:7:42)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xxx/StableDiffusion/ComfyUIMini/node_modules/uuid/dist/rng.js',
    '/home/xxx/StableDiffusion/ComfyUIMini/node_modules/uuid/dist/v1.js',
    '/home/xxx/StableDiffusion/ComfyUIMini/node_modules/uuid/dist/index.js',
    '/home/xxx/StableDiffusion/ComfyUIMini/src/utils/generation.js',
    '/home/xxx/StableDiffusion/ComfyUIMini/src/routes/wsRouter.js',
    '/home/xxx/StableDiffusion/ComfyUIMini/src/index.js'
  ]
}
`
crypto is built in now, so not sure what the problem is. Tried adding  const crypto = require('crypto'); to no avail.

**Comment by nitrousoxXxide** [comment]
Fixed by upgrading from nod 12 ->node 20.

**Comment by ImDarkTom** [comment]
I've replaced the uuid package with crypto.randomUUID() and set a minimum nodejs version in the package.json. Thanks for bringing this to my attention.
