### ISSUE TITLE
Cant read workflows folder

### ISSUE THREAD

**Issue by benpetro97** [ImDarkTom/ComfyUIMini#5]
Not sure whats causing this, I've tried on windows and Arch but neither seem to be able to launch.

[ben@bens-desktop-EOS ComfyUIMini]$ node .
[INFO] Found 1 workflows in the workflow folder.
Error reading workflows folder:  TypeError: Cannot read properties of undefined (reading 'title')
    at checkWorkflowCache (/home/hdd/AI/ComfyUI-Installer/ComfyUIMini/src/utils/workflowCache.js:51:83)
    at checkForWorkflowsFolder (/home/hdd/AI/ComfyUI-Installer/ComfyUIMini/src/utils/fileManager.js:21:9)
    at Object.<anonymous> (/home/hdd/AI/ComfyUI-Installer/ComfyUIMini/src/index.js:32:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:166:5)
[WARN] Invalid directory for checkpoint in model_dirs.json
[INFO] Loaded 4 model types.
[SUCCESS] Running on http://10.0.0.97:3000
[WARN] ECONNREFUSED: Make sure ComfyUI is running and is accessible at the URL in the config.json file.

Any idea whats going on here? I saved my workflow APIs using the dev tool on comfyUI

**Comment by benpetro97** [comment]
Also, these are correct folder directories for models, but on boot I am getting error for invalid directory. Is something wrong here?

![image](https://github.com/user-attachments/assets/4522b4fc-4ad6-4c58-8a6a-64c13e20de49)

**Comment by ImDarkTom** [comment]
> Error reading workflows folder: TypeError: Cannot read properties of undefined (reading 'title')

This should be fixed in the latest commit. As for the issue regarding invalid directory for models, this is being worked on
